import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Trash2,FolderCog,Users,ShieldCheck} from 'lucide-react';
import {EditDialog,Field,ErrorBox,TYPES,stableSubmit,when} from './kit';

export function RulesEditor({rules,onChange,config}){
    const [entries,setEntries]=useState(()=>{const rows=[];for(const r of rules){let x=rows.find(v=>v.type===r.principal_type&&Number(v.id)===Number(r.principal_id));if(!x){x={type:r.principal_type,id:r.principal_id,permissions:{}};rows.push(x);}x.permissions[r.action]=r.effect;}return rows;});
    function update(next){setEntries(next);onChange(next.flatMap(r=>Object.entries(r.permissions).filter(([,effect])=>effect).map(([action,effect])=>({principal_type:r.type,principal_id:Number(r.id),action,effect}))));}
    return <div className="dc-rules"><p className="dc-help">未配置的操作默认不开放；明确禁止优先。分类位置不继承权限。单条资料选择独立权限后，将完整替代分类规则。</p>
        {entries.map((r,i)=><fieldset key={i}><legend>授权对象 {i+1}</legend><div className="dc-rule-subject"><select aria-label={`授权对象${i+1}类型`} value={r.type} onChange={e=>update(entries.map((x,j)=>j===i?{...x,type:e.target.value,id:e.target.value==='everyone'?0:(config[e.target.value==='user'?'users':'groups'][0]?.id||0)}:x))}><option value="user">指定人员</option><option value="group">工作组</option><option value="everyone">所有在用人员</option></select>{r.type!=='everyone'&&<select aria-label={`授权对象${i+1}名称`} value={r.id} onChange={e=>update(entries.map((x,j)=>j===i?{...x,id:Number(e.target.value)}:x))}>{config[r.type==='user'?'users':'groups'].map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select>}<button type="button" className="dc-icon" aria-label={`移除授权对象${i+1}`} onClick={()=>update(entries.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>
            <div className="dc-inline dc-rule-presets">{[['只读',['discover','view']],['审核',['discover','view','review']],['维护与发布',Object.keys(config.actions)],['清空',[]]].map(([label,actions])=><button key={label} type="button" className="dc-text-button" onClick={()=>update(entries.map((x,j)=>j===i?{...x,permissions:Object.fromEntries(actions.map(a=>[a,'allow']))}:x))}>{label}</button>)}</div>
            <div className="dc-permission-grid">{Object.entries(config.actions).map(([action,label])=><Field label={label} key={action}><select value={r.permissions[action]||''} className={r.permissions[action]||'unset'} onChange={e=>update(entries.map((x,j)=>j===i?{...x,permissions:{...x.permissions,[action]:e.target.value}}:x))}><option value="">未授权</option><option value="allow">允许</option><option value="deny">禁止</option></select></Field>)}</div></fieldset>)}
        <button type="button" className="btn btn-default" onClick={()=>update([...entries,{type:'user',id:config.users[0]?.id||0,permissions:{}}])}><Plus size={15}/>添加授权对象</button></div>;
}
export function SchemaEditor({fields,onChange}){
    return <div className="dc-schema">{fields.map((f,i)=><div className="dc-schema-row" key={f.key}><input aria-label={`字段${i+1}名称`} placeholder="字段名称" value={f.label} required maxLength={50} onChange={e=>onChange(fields.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/><select aria-label={`字段${i+1}类型`} value={f.type} onChange={e=>onChange(fields.map((x,j)=>j===i?{...x,type:e.target.value}:x))}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><label className="dc-check"><input type="checkbox" checked={f.required} onChange={e=>onChange(fields.map((x,j)=>j===i?{...x,required:e.target.checked}:x))}/>必填</label><button type="button" className="dc-icon" aria-label={`删除字段${i+1}`} onClick={()=>onChange(fields.filter((_,j)=>j!==i))}><Trash2 size={16}/></button>{f.type==='select'&&<input className="dc-options" aria-label={`字段${i+1}选项`} placeholder="选项以中文逗号分隔" value={f.options.join('，')} onChange={e=>onChange(fields.map((x,j)=>j===i?{...x,options:e.target.value.split(/[，,]/)}:x))}/>}</div>)}<button type="button" className="btn btn-default" disabled={fields.length>=30} onClick={()=>onChange([...fields,{key:'field_'+crypto.randomUUID().slice(0,8),label:'',type:'text',required:false,options:[]}])}><Plus size={15}/>添加字段</button><p className="dc-help">编号与名称为固定字段。已有资料的字段可改名或增加，不能删除或改变类型；历史版本保留原字段快照。</p></div>;
}
export default function Administration({api,onChanged}){
    const [config,setConfig]=useState(null),[error,setError]=useState(''),[editor,setEditor]=useState(null),[tab,setTab]=useState('category');const submit=useMemo(()=>stableSubmit(api),[api]);
    const load=()=>api.get('/configuration').then(setConfig).catch(e=>{setConfig(null);setError(e.message);});useEffect(()=>{load();},[api]);
    function category(c){setEditor({kind:'category',id:c?.id||0,value:c?{...c,enabled:!!c.enabled,rules:config.rules.filter(r=>r.scope_type==='category'&&r.scope_id===c.id)}:{name:'',description:'',parent_id:null,position:0,enabled:true,fields:[],rules:[]}});}
    return <section className="dc-admin"><div className="dc-toolbar"><div className="dc-inline"><button className={`btn ${tab==='category'?'btn-primary':'btn-default'}`} onClick={()=>setTab('category')}><FolderCog size={16}/>分类与字段</button><button className={`btn ${tab==='group'?'btn-primary':'btn-default'}`} onClick={()=>setTab('group')}><Users size={16}/>工作组</button></div>{config&&<button className="btn btn-primary" onClick={()=>tab==='category'?category(null):setEditor({kind:'group',id:0,value:{name:'',members:[]}})}><Plus size={16}/>{tab==='category'?'新建分类':'新建工作组'}</button>}</div><ErrorBox error={error}/>
        <p className="dc-help"><ShieldCheck size={15}/>配置权限与资料查看权限分别控制。工作组用于授权，不代表企业部门隶属关系。</p>
        {!config&&!error?<p className="dc-empty">正在读取配置…</p>:config&&<div className="dc-list">{config[tab==='category'?'categories':'groups'].map(x=><button key={x.id} className="dc-admin-row" onClick={()=>tab==='category'?category(x):setEditor({kind:'group',id:x.id,value:x})}><span>{tab==='category'?<FolderCog size={19}/>:<Users size={19}/>}<strong>{x.name}</strong></span><span className="dc-muted">{tab==='category'?`${x.enabled?'使用中':'已停用'} · ${x.fields.length}个字段 · ${config.rules.filter(r=>r.scope_type==='category'&&r.scope_id===x.id).length?'已配置权限':'尚未授权'}`:`${x.members.length}位成员`} ›</span></button>)}{!config[tab==='category'?'categories':'groups'].length&&<div className="dc-empty">尚未建立{tab==='category'?'分类':'工作组'}，可以从右上角新增。</div>}</div>}
        {config?.events?.length>0&&<details className="dc-config-history"><summary>配置变更记录</summary>{config.events.map(e=><article key={e.id}><strong>{e.label} · {e.detail.configuration?.name||'单条资料'}</strong><small>{e.actor} · {when(e.created_at)}</small>{e.detail.configuration?.members&&<p>成员：{e.detail.configuration.members.map(id=>config.users.find(u=>u.id===Number(id))?.name||'已停用人员').join('、')||'无'}</p>}{e.detail.configuration?.fields&&<p>字段：{e.detail.configuration.fields.map(f=>f.label).join('、')||'仅编号与名称'}</p>}{e.detail.configuration?.rules&&<details><summary>查看当次授权结果</summary>{e.detail.configuration.rules.map((r,i)=><p key={i}>{r.principal_type==='everyone'?'所有在用人员':config[r.principal_type==='user'?'users':'groups'].find(u=>u.id===Number(r.principal_id))?.name||'已停用对象'} · {config.actions[r.action]} · {r.effect==='allow'?'允许':'禁止'}</p>)}{!e.detail.configuration.rules.length&&<p>无单独授权规则</p>}</details>}</article>)}</details>}
        {editor&&<EditDialog key={`${editor.kind}:${editor.id}`} title={editor.kind==='category'?'分类、字段与权限':'工作组成员'} initial={editor.value} wide onClose={()=>setEditor(null)} onSave={async value=>{await submit(`/catalog/${editor.kind}/${editor.id}`,value);await load();onChanged();}}>{(v,set)=><><Field label="名称"><input value={v.name} required maxLength={80} onChange={e=>set({...v,name:e.target.value})}/></Field>{editor.kind==='group'?<fieldset><legend>工作组成员</legend><div className="dc-members">{config.users.map(u=><label key={u.id} className="dc-check"><input type="checkbox" checked={v.members.map(Number).includes(u.id)} onChange={e=>set({...v,members:e.target.checked?[...v.members,u.id]:v.members.filter(id=>Number(id)!==u.id)})}/>{u.name}</label>)}</div><p className="dc-help">成员移出后，后续请求立即按新权限校验。</p></fieldset>:<><div className="dc-form-grid"><Field label="上级资料目录"><select value={v.parent_id||''} onChange={e=>set({...v,parent_id:Number(e.target.value)||null})}><option value="">顶层目录</option>{config.categories.filter(c=>c.id!==editor.id).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="排序"><input type="number" min="0" max="10000" required value={v.position} onChange={e=>set({...v,position:Number(e.target.value)})}/></Field></div><Field label="分类说明"><textarea rows={2} value={v.description||''} maxLength={2000} onChange={e=>set({...v,description:e.target.value})}/></Field><label className="dc-check"><input type="checkbox" checked={v.enabled} onChange={e=>set({...v,enabled:e.target.checked})}/>启用分类</label><h3>台账字段</h3><SchemaEditor fields={v.fields} onChange={fields=>set({...v,fields})}/><h3>默认权限</h3><RulesEditor rules={v.rules} onChange={rules=>set({...v,rules})} config={config}/></>}</>}</EditDialog>}
    </section>;
}
