import React,{useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Inbox} from 'lucide-react';
import {Badge,EditDialog,ErrorBox,Field,when,stableSubmit} from './kit';
export default function Collaboration({api,userId,refresh,onOpen,onChanged}){
    const [data,setData]=useState(null),[error,setError]=useState(''),[done,setDone]=useState(false),[scope,setScope]=useState('mine'),[form,setForm]=useState(null),[type,setType]=useState('');
    const submit=useMemo(()=>stableSubmit(api),[api,form]);
    useEffect(()=>{const abort=new AbortController();setError('');api.get('/collaboration',abort.signal).then(setData).catch(e=>{if(!abort.signal.aborted){setData(null);setError(e.message);}});return()=>abort.abort();},[api,refresh]);
    const names=id=>data?.users.find(u=>u.id===Number(id))?.name||'已停用人员';
    const items=data?.items.filter(i=>(!type||i.type===type)&&(scope==='all'||Number(i[scope==='mine'?'assignee_id':'actor_id'])===Number(userId))&&(done||['pending','open','accepted','blocked'].includes(i.state)))||[];
    const action=(i,decision,label)=>setForm({item:i,decision,label});
    return <section><div className="dc-toolbar"><div className="dc-inline"><select aria-label="协作范围" value={scope} onChange={e=>setScope(e.target.value)}><option value="mine">交给我的</option><option value="sent">我发起的</option><option value="all">与我相关</option></select><select aria-label="协作类型" value={type} onChange={e=>setType(e.target.value)}><option value="">全部类型</option><option value="review">资料审核</option><option value="access">查看申请</option><option value="task">协作任务</option></select><label className="dc-check"><input type="checkbox" checked={done} onChange={e=>setDone(e.target.checked)}/>包含已处理</label></div><span className="dc-muted">{items.length}项</span></div><ErrorBox error={error}/>
        {!data&&!error?<p className="dc-empty">正在读取协作事项…</p>:!items.length&&!error?<div className="dc-empty"><Inbox size={28}/><h3>当前没有待处理事项</h3><p>资料审核、查看申请和派发任务会在这里汇总。</p></div>:<div className="dc-collaboration-list">{items.map(i=><article key={`${i.type}:${i.id}`}><div className="dc-section-heading"><div><small>{{review:'资料审核',access:'查看申请',task:'协作任务'}[i.type]}</small><h3>{i.title}</h3></div><Badge state={i.state}/></div><button className="dc-text-button" onClick={()=>onOpen({id:i.record_id,version:i.version_id})}>{i.record_title}<ArrowUpRight size={15}/></button><p>{i.description||i.reason}</p><div className="dc-collaboration-meta"><span>{names(i.actor_id)} → {names(i.assignee_id)}</span><span>{i.due_date?`完成日期 ${i.due_date}`:i.expires_at?`有效至 ${when(i.expires_at)}`:when(i.created_at)}</span></div>{(i.result||i.decision_note)&&<p className="dc-notice">处理意见：{i.result||i.decision_note}</p>}
            <div className="dc-action-row">{i.type==='review'&&i.can_act&&<button className="btn btn-primary" onClick={()=>onOpen({id:i.record_id,version:i.version_id})}>核对资料</button>}{i.type==='access'&&<>{i.can_act&&i.state==='pending'&&<><button className="btn btn-primary" onClick={()=>action(i,'approve','批准限时查看')}>批准查看</button><button className="btn btn-default" onClick={()=>action(i,'reject','拒绝查看申请')}>拒绝</button></>}{i.can_act&&i.state==='approved'&&<button className="btn btn-default" onClick={()=>action(i,'revoke','撤销临时查看')}>撤销授权</button>}{i.state==='pending'&&Number(i.actor_id)===Number(userId)&&<button className="btn btn-default" onClick={()=>action(i,'cancel','撤回查看申请')}>撤回申请</button>}</>}{i.type==='task'&&i.can_act&&['open','accepted','blocked'].includes(i.state)&&<>{Number(i.assignee_id)===Number(userId)&&<>{i.state!=='accepted'&&<button className="btn btn-default" onClick={()=>action(i,'accept','接收协作任务')}>接收</button>}<button className="btn btn-default" onClick={()=>action(i,'block','等待补充资料')}>需补充</button><button className="btn btn-primary" onClick={()=>action(i,'complete','完成协作任务')}>填写结果</button></>}{Number(i.actor_id)===Number(userId)&&<button className="btn btn-default" onClick={()=>action(i,'cancel','取消协作任务')}>取消任务</button>}</>}</div></article>)}</div>}
        {form&&<EditDialog title={form.label} initial={{note:''}} onClose={()=>setForm(null)} label="确认处理" onSave={async v=>{const i=form.item;await submit(`/collaboration/${i.id}/${i.type==='task'?'task':'access'}-action`,{decision:form.decision,revision:i.revision,note:v.note,result:v.note});onChanged();}}>{(v,set)=><><p className="dc-help">{form.item.record_title} · {form.item.title}</p><Field label="处理说明 *"><textarea required rows={4} maxLength={2000} value={v.note} onChange={e=>set({...v,note:e.target.value})}/></Field></>}</EditDialog>}
    </section>;
}
