import React,{useEffect,useMemo,useState} from 'react';
import {Folder,FolderOpen,FileText,Search,Plus,RotateCw,Download,ChevronLeft,ChevronRight,Database,LockKeyhole} from 'lucide-react';
import {Segments,Entrance} from '../../ui/WorkspaceKit';
import {Badge,EditDialog,ErrorBox,Field,ValuesEditor,makeApi,when,stableSubmit} from './kit';
import RecordDetail from './RecordDetail';
import Administration from './Administration';
import Collaboration from './Collaboration';
import Imports from './Imports';
import '../../../css/company-data.css';

function Tree({categories,value,onChange}){
    function children(parent,depth=0){return categories.filter(c=>Number(c.parent_id||0)===Number(parent||0)).map(c=><React.Fragment key={c.id}><button className={Number(value)===c.id?'is-selected':''} style={{paddingLeft:12+depth*16}} onClick={()=>onChange(String(c.id))} aria-current={Number(value)===c.id?'page':undefined}>{Number(value)===c.id?<FolderOpen size={16}/>:<Folder size={16}/>}<span>{c.name}</span></button>{children(c.id,depth+1)}</React.Fragment>);}
    return <nav className="dc-tree" aria-label="资料分类"><span className="dc-eyebrow">资料目录</span><button className={!value?'is-selected':''} onClick={()=>onChange('')}><Database size={16}/>全部可见资料</button>{children(null)}</nav>;
}
export default function CompanyData({endpoint}){
    const api=useMemo(()=>makeApi(endpoint),[endpoint]),submit=useMemo(()=>stableSubmit(api),[api]);
    const initial=new URLSearchParams(location.search);const [tab,setTab]=useState(['records','collaboration','imports','admin'].includes(initial.get('tab'))?initial.get('tab'):'records'),[category,setCategory]=useState(''),[q,setQ]=useState(''),[state,setState]=useState(''),[archived,setArchived]=useState(false),[page,setPage]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[create,setCreate]=useState(false),[selection,setSelection]=useState(initial.get('record')?{id:Number(initial.get('record')),version:Number(initial.get('version'))||null}:null),[notice,setNotice]=useState('');
    useEffect(()=>{setPage(1);},[q,category,state,archived]);
    useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{const params=new URLSearchParams({q,category,state,archived:archived?'1':'0',page:String(page)});for(const [k,v] of [...params])if(v==='')params.delete(k);api.get(`?${params}`,abort.signal).then(d=>{setData(d);if(d.page!==page)setPage(d.page);}).catch(e=>{if(!abort.signal.aborted){setError(e.message);setData(null);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});},q?180:0);return()=>{clearTimeout(timer);abort.abort();};},[api,q,category,state,archived,page,refresh]);
    useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
    useEffect(()=>{if(data&&!data.manager&&tab==='admin')setTab('records');},[data,tab]);
    const changed=()=>{setRefresh(x=>x+1);setNotice('已保存，记录已更新。');};
    const cat=data?.categories.find(c=>c.id===Number(category));
    function select(s){setSelection(s);const url=new URL(location.href);url.searchParams.set('record',s.id);if(s.version)url.searchParams.set('version',s.version);else url.searchParams.delete('version');history.replaceState(null,'',url);}
    function close(){setSelection(null);const url=new URL(location.href);url.searchParams.delete('record');url.searchParams.delete('version');history.replaceState(null,'',url);}
    function changeTab(value){setTab(value);const url=new URL(location.href);url.searchParams.set('tab',value);history.replaceState(null,'',url);}
    return <div className="dc-app"><div className="dc-page-heading"><div><div className="dc-eyebrow">共享依据 · 有序协作</div><h2>公司资料</h2></div><div className="dc-inline"><span className="dc-save-status" role="status">{notice}</span><button className="dc-icon" aria-label="刷新公司资料" onClick={()=>setRefresh(x=>x+1)}><RotateCw size={18} className={loading?'dc-spinning':''}/></button></div></div>
        <Segments value={tab} onChange={changeTab} label="公司资料工作区" items={[['records','资料与台账'],['collaboration','协作待办'],['imports','导入记录'],...(data?.manager?[['admin','分类与权限']]:[])]}/><ErrorBox error={error}/>
        {tab==='records'&&<div className="dc-workspace"><Tree categories={data?.categories||[]} value={category} onChange={setCategory}/><section className="dc-records"><div className="dc-toolbar"><div className="dc-search"><Search size={17}/><input aria-label="搜索资料" placeholder="搜索名称、编号或已授权的内容" value={q} maxLength={200} onChange={e=>setQ(e.target.value)}/></div><div className="dc-inline">{cat?.abilities.export&&<a className="btn btn-default" href={`${api.base}/export/${cat.id}`}><Download size={15}/>导出台账</a>}{cat?.abilities.create&&cat?.abilities.view&&<button className="btn btn-primary" onClick={()=>setCreate(true)}><Plus size={16}/>新建资料</button>}</div></div>
            <div className="dc-list-meta"><div className="dc-inline"><strong>{cat?.name||'全部可见资料'}</strong><span className="dc-muted">{data?.total??0}项</span></div><div className="dc-inline"><select aria-label="资料状态" value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option><option value="published">已发布</option><option value="draft">草稿</option><option value="pending">待审核</option><option value="rejected">已退回</option><option value="withdrawn">已撤回</option></select><label className="dc-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>归档资料</label></div></div>
            {loading&&!data?<p className="dc-empty">正在读取资料…</p>:data?.items.length?<div className="dc-table-wrap"><table><thead><tr><th>资料名称</th><th>分类</th><th>版本 / 状态</th><th>更新时间</th></tr></thead><tbody>{data.items.map(r=><tr key={r.id}><td><button className="dc-record-link" onClick={()=>select({id:r.id})}>{r.readable?<FileText size={19}/>:<LockKeyhole size={18}/>}<span><strong>{r.title}</strong><small>{r.code} · {r.kind==='ledger'?'台账':'文件资料'}</small></span></button></td><td className="dc-category-cell">{data.categories.find(c=>c.id===r.category_id)?.name}</td><td><span className="dc-version">第{r.version}版</span><Badge state={r.state}/></td><td>{when(r.updated_at)}</td></tr>)}</tbody></table></div>:!error&&<Entrance className="dc-empty"><FolderOpen size={30}/><h3>{q||state?'没有符合条件的资料':archived?'这里没有归档资料':'从资料目录开始'}</h3><p>{q||state?'调整关键词或状态后重试。':cat?.abilities.create?'点击“新建资料”，或通过导入记录批量上传旧台账。':'选择左侧分类查看资料。仅显示你有权限发现的内容。'}</p></Entrance>}
            {data&&data.pages>1&&<div className="dc-pagination"><span>第{data.page}页，共{data.pages}页</span><button className="dc-icon" aria-label="上一页" disabled={data.page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><button className="dc-icon" aria-label="下一页" disabled={data.page>=data.pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div>}
        </section></div>}
        {data&&tab==='collaboration'&&<Collaboration api={api} userId={data.user_id} refresh={refresh} onOpen={select} onChanged={changed}/>}
        {data&&tab==='imports'&&<Imports api={api} categories={data.categories} refresh={refresh} onChanged={changed}/>}
        {data?.manager&&tab==='admin'&&<Administration api={api} onChanged={changed}/>}
        {selection&&data&&<RecordDetail key={`${selection.id}:${selection.version||''}`} api={api} selection={selection} userId={data.user_id} manager={data.manager} onClose={close} onChanged={changed}/>}
        {create&&cat&&<EditDialog title={`新建资料 · ${cat.name}`} initial={{code:'',title:'',kind:'ledger',values:{},note:'首次建立'}} onClose={()=>setCreate(false)} label="保存草稿" onSave={async value=>{const result=await submit(`/records/${cat.id}/create`,{...value,category_revision:cat.revision});changed();select({id:result.id});}}>{(v,set)=><><div className="dc-form-grid"><Field label="资料编号 *"><input required maxLength={80} value={v.code} onChange={e=>set({...v,code:e.target.value})} placeholder="同一分类内不可重复"/></Field><Field label="资料类型"><select value={v.kind} onChange={e=>set({...v,kind:e.target.value})}><option value="ledger">结构化台账</option><option value="file">文件资料</option></select></Field></div><Field label="资料名称 *"><input required maxLength={180} value={v.title} onChange={e=>set({...v,title:e.target.value})}/></Field><ValuesEditor fields={cat.fields} values={v.values} onChange={values=>set({...v,values})}/><Field label="建立说明 *"><textarea required rows={2} maxLength={2000} value={v.note} onChange={e=>set({...v,note:e.target.value})}/></Field>{v.kind==='file'&&<p className="dc-help">保存后上传附件，再提交审核发布。</p>}</>}</EditDialog>}
    </div>;
}
