import React,{useEffect,useState} from 'react';
import {Upload,Download,FileSpreadsheet,CheckCircle2} from 'lucide-react';
import {SurfaceDialog} from '../../ui/WorkspaceKit';
import {confirmAction} from '../../ui/confirmAction';
import {Badge,ErrorBox,Field,useWrite,when} from './kit';
function Batch({api,id,onClose,onChanged}){
    const [data,setData]=useState(null),[mapping,setMapping]=useState({}),[error,setError]=useState(''),[revision,setRevision]=useState(0);const mutation=useWrite(api);
    useEffect(()=>{const abort=new AbortController();api.get(`/imports/${id}`,abort.signal).then(d=>{setData(d);setMapping(d.mapping);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[api,id,revision]);
    const dirty=data&&JSON.stringify(mapping)!==JSON.stringify(data.mapping);
    async function close(){if(mutation.busy)return;if(!dirty||await confirmAction('字段映射尚未校验保存，是否放弃修改？',{confirmLabel:'放弃修改'}))onClose();}
    async function act(action){if(action==='commit'&&!await confirmAction(`将写入${data.count}条台账草稿，审核发布后其他人员才可查看。`,{title:'确认导入',confirmLabel:'生成草稿'}))return;if(action==='undo'&&!await confirmAction('仅未修改、未协作的本批草稿可以整批撤销。撤销后保留归档记录。',{title:'撤销导入',confirmLabel:'确认撤销'}))return;
        const result=await mutation.write(`/imports/${id}`,{action,mapping});if(result){setRevision(v=>v+1);onChanged();}}
    const errors=data?.rows?.filter(r=>r.errors.length).length||0;
    return <SurfaceDialog title="导入核对" onClose={close} className="dc-dialog dc-wide"><div className="dc-dialog-body"><ErrorBox error={error||mutation.error}/>{data?<><div className="dc-section-heading"><h3>{data.filename}</h3><Badge state={data.state}/></div><p className="dc-help">{data.category} · {data.count}行 · 仅你可以查看这个导入批次</p>{data.state==='preview'?<>{data.stale&&<div className="dc-error">分类配置已变化，请取消本批次并重新上传。</div>}<div className="dc-form-grid">{[{key:'code',label:'编号',required:true},{key:'title',label:'名称',required:true},...data.fields].map(f=><Field key={f.key} label={`${f.label}${f.required?' *':''}`}><select value={mapping[f.key]||''} onChange={e=>setMapping({...mapping,[f.key]:e.target.value})}><option value="">不导入此列</option>{data.headers.map(h=><option key={h}>{h}</option>)}</select></Field>)}</div><div className="dc-section-heading"><h3>{dirty?'映射已修改，需重新校验':errors?`${errors}行需要修正`:'校验通过，可以生成草稿'}</h3><button className="btn btn-default" disabled={mutation.busy||data.stale} onClick={()=>act('map')}>保存映射并校验</button></div><div className="dc-table-wrap"><table><thead><tr><th>原始行</th><th>编号</th><th>名称</th><th>校验结果</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.code||'—'}</td><td>{r.title||'—'}</td><td className={r.errors.length?'dc-error-text':'dc-allowed'}>{r.errors.join('；')||'通过'}</td></tr>)}</tbody></table></div><p className="dc-help">内容错误请修改源文件后重新上传。确认时会再次校验，任何一行失败都不会部分写入。</p></>:<div className="dc-empty"><CheckCircle2 size={28}/><h3>{data.state==='committed'?`已生成${data.result.length}条草稿`:'该批次已结束'}</h3><p>原文件与导入来源记录保留，可在资料列表继续审核。</p></div>}</>:!error&&<p className="dc-empty">正在读取导入批次…</p>}</div><footer>{data?.state==='preview'?<><button className="btn btn-default" disabled={mutation.busy} onClick={()=>act('cancel')}>取消本批次</button><button className="btn btn-primary" disabled={mutation.busy||errors>0||dirty||data.stale} onClick={()=>act('commit')}>{mutation.busy?'正在处理…':'确认生成草稿'}</button></>:data?.state==='committed'?<><button className="btn btn-default" disabled={mutation.busy} onClick={()=>act('undo')}>撤销未使用草稿</button><a className="btn btn-primary" href={`${api.base.replace(/\/api$/, '')}?record=${data.result[0]}`}>打开首条草稿</a></>:<button className="btn btn-default" onClick={close}>关闭</button>}</footer></SurfaceDialog>;
}
export default function Imports({api,categories,refresh,onChanged}){
    const [data,setData]=useState(null),[category,setCategory]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(null);const mutation=useWrite(api);const eligible=categories.filter(c=>c.abilities.create&&c.abilities.view);
    useEffect(()=>{const abort=new AbortController();setError('');api.get('/imports',abort.signal).then(setData).catch(e=>{if(!abort.signal.aborted){setData(null);setError(e.message);}});return()=>abort.abort();},[api,refresh]);
    return <section><div className="dc-toolbar"><div className="dc-inline"><select aria-label="导入目标分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="">选择导入分类</option>{eligible.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{category&&<a className="btn btn-default" href={`${api.base}/export/${category}?template=1`}><Download size={15}/>下载模板</a>}</div><label className={`btn btn-primary ${!category||mutation.busy?'disabled':''}`}><Upload size={15}/>{mutation.busy?'正在上传…':'上传表格'}<input className="dc-file-input" type="file" accept=".csv,.xlsx" aria-label="上传导入表格" disabled={!category||mutation.busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const p=new FormData();p.append('file',f);const result=await mutation.write(`/imports/stage/${category}`,p);if(result){setSelected(result.id);onChanged();}e.target.value='';}}/></label></div><p className="dc-help">上传旧台账 → 对应字段 → 校验 → 生成草稿。支持 UTF-8 CSV、单工作表 XLSX，每批最多500行、50列、5 MB。公式需先粘贴为值。</p><ErrorBox error={error||mutation.error}/>
        {!data&&!error?<p className="dc-empty">正在读取导入记录…</p>:data?.items.length?<div className="dc-list">{data.items.map(b=><button key={b.id} className="dc-admin-row" onClick={()=>setSelected(b.id)}><span><FileSpreadsheet size={20}/><span><strong>{b.filename}</strong><small>{b.category} · {b.count}行 · {when(b.created_at)}</small></span></span><Badge state={b.state}/></button>)}</div>:<div className="dc-empty"><FileSpreadsheet size={28}/><h3>从一张已有表格开始</h3><p>先选择资料分类，下载模板或上传旧台账。</p></div>}
        {selected&&<Batch api={api} id={selected} onClose={()=>setSelected(null)} onChanged={onChanged}/>}
    </section>;
}
