<script setup>
import { reactive,ref,computed,watch,onMounted,onUnmounted } from 'vue'
import { useWorkspace } from './useWorkspace'
import { stamp,activityRows } from './utils'
import Button from './components/UiButton.vue'
import AppIcon from './components/AppIcon.vue'
import StatusBadge from './components/StatusBadge.vue'
import EmptyState from './components/EmptyState.vue'
import DownloadButton from './components/DownloadButton.vue'
import WorkspaceForm from './components/WorkspaceForm.vue'
import DocumentsPanel from './components/DocumentsPanel.vue'
import AiPanel from './AiPanel.vue'
import './ai.css'

const w=reactive(useWorkspace()), taskFilter=ref('open')
const taskRows=computed(()=>w.selected?.tasks.filter(t=>taskFilter.value==='all'||(taskFilter.value==='done'?t.status==='已完成':t.status!=='已完成'))||[])
const inboxTabs=[['all','全部'],['reply','待我回复'],['confirm','待我确认'],['ai','AI 待处理'],['held','已挂起']]
const detailTabs=[['overview','概览'],['documents','资料'],['tasks','协作'],['ai','AI 辅助'],['activities','历史']]
const columnNames={business:'业务类型',people:'负责人',date:'期望交期',status:'状态',updated:'最近更新'}
const title=computed(()=>w.view==='tasks'?'我的工作':w.view==='detail'?'询价详情':'询价协作')
watch(()=>[w.selected?.name,w.target],()=>{taskFilter.value=w.target?'all':'open'})
function focusMain(){document.getElementById('main-content')?.focus()}
function closePopovers(event){document.querySelectorAll('details.popover[open]').forEach(el=>{if(!el.contains(event.target)||event.key==='Escape')el.open=false})}
function menuAction(action){document.querySelectorAll('details.popover[open]').forEach(el=>el.open=false);action()}
function tabKey(event,index){let next=index;if(event.key==='ArrowRight')next=(index+1)%detailTabs.length;else if(event.key==='ArrowLeft')next=(index+detailTabs.length-1)%detailTabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=detailTabs.length-1;else return;event.preventDefault();w.changeTab(detailTabs[next][0]);event.currentTarget.parentElement.children[next]?.focus()}
async function copyLink(){try{await navigator.clipboard.writeText(location.href);w.notify('页面链接已复制。')}catch{w.error='无法复制，请从地址栏复制此页面链接。'}}
onMounted(()=>{document.addEventListener('click',closePopovers);document.addEventListener('keydown',closePopovers)})
onUnmounted(()=>{document.removeEventListener('click',closePopovers);document.removeEventListener('keydown',closePopovers)})
</script>

<template>
  <div :class="['app-shell',w.density,{'sidebar-collapsed':w.collapsed,'nav-open':w.mobileNav}]">
    <a class="skip-link" href="#main-content" @click.prevent="focusMain">跳到主要内容</a>
    <button v-if="w.mobileNav" class="nav-overlay" aria-label="收起导航" @click="w.mobileNav=false"></button>
    <aside class="sidebar">
      <a class="brand" href="#/inquiries" aria-label="京能协作"><span class="brand-mark">京</span><span class="brand-text">京能协作<small>工作空间</small></span></a>
      <nav aria-label="主导航">
        <a href="#/tasks" :class="['nav-link',{active:w.view==='tasks'}]" :aria-current="w.view==='tasks'?'page':undefined" title="我的工作"><AppIcon name="inbox" /><span class="nav-label">我的工作</span><span v-if="w.inbox.counts.all" class="nav-count">{{ w.inbox.counts.all }}</span></a>
        <a href="#/inquiries" :class="['nav-link',{active:w.view!=='tasks'}]" :aria-current="w.view!=='tasks'?'page':undefined" title="询价协作"><AppIcon name="list" /><span class="nav-label">询价协作</span></a>
      </nav>
      <div class="sidebar-spacer"></div>
      <div class="environment"><span></span><span class="nav-label">演示空间</span></div>
      <details v-if="w.boot" class="popover account-menu"><summary class="account-trigger" :title="w.boot.full_name"><span class="avatar">{{ w.boot.full_name?.slice(0,1) }}</span><span class="account-name"><strong>{{ w.boot.full_name }}</strong><small>{{ w.boot.can_create?'销售工作空间':'技术工作空间' }}</small></span><AppIcon name="down" /></summary><div class="popover-content"><a v-if="w.boot.can_manage" href="/foundation"><AppIcon name="settings" />基础环境管理</a><button @click="menuAction(w.logout)"><AppIcon name="logout" />退出登录</button></div></details>
    </aside>
    <main class="main">
      <header class="topbar"><Button class="desktop-only" icon="panel" variant="ghost" :aria-label="w.collapsed?'展开导航':'收起导航'" @click="w.collapsed=!w.collapsed" /><Button class="mobile-only" icon="menu" variant="ghost" aria-label="打开导航" @click="w.mobileNav=true" /><div class="breadcrumb"><button v-if="w.view==='detail'" @click="w.backToList">询价协作</button><template v-else>工作空间</template><AppIcon name="right" /><span>{{ title }}</span></div><span class="grow"></span><span class="environment-label">演示数据</span><Button icon="refresh" variant="ghost" aria-label="刷新当前页面" :loading="w.loading" :disabled="w.busy" @click="w.refresh" /></header>
      <div v-if="w.notice" class="toast" role="status"><AppIcon name="circleCheck" /><span>{{ w.notice }}</span><button aria-label="关闭通知" @click="w.notice=''"><AppIcon name="close" /></button></div>
      <div id="main-content" data-scroll-area class="workspace-content" tabindex="-1" @scroll.passive="w.storeScroll">
        <div v-if="w.error" class="message error" role="alert"><AppIcon name="warning" /><p>{{ w.error }}</p><Button v-if="w.boot" :disabled="w.busy" @click="w.refresh">重新读取</Button><a v-else class="button secondary" href="/signin">重新登录</a></div>
        <template v-if="w.view==='inquiries'">
          <div class="page-heading"><div class="heading-inline"><h1>询价协作</h1><span class="count">{{ w.total }}</span></div><div class="toolbar-actions"><details class="popover view-options"><summary class="button secondary" aria-label="视图设置"><AppIcon name="settings" /><span>视图</span></summary><div class="popover-content"><strong class="menu-label">显示密度</strong><button :class="{chosen:w.density==='compact'}" @click="w.density='compact'"><AppIcon name="compact" />紧凑<AppIcon v-if="w.density==='compact'" name="check" /></button><button :class="{chosen:w.density==='comfortable'}" @click="w.density='comfortable'"><AppIcon name="comfortable" />舒适<AppIcon v-if="w.density==='comfortable'" name="check" /></button><hr><strong class="menu-label">显示列</strong><label v-for="(label,k) in columnNames" :key="k"><input type="checkbox" v-model="w.columns[k]">{{ label }}</label></div></details><Button v-if="w.boot?.can_create" variant="primary" icon="plus" @click="w.editInquiry(true)">新建询价</Button></div></div>
          <div class="list-toolbar">
            <div class="segmented" aria-label="业务类型"><button v-for="kind in ['','成套','钣金']" :key="kind" :class="{selected:w.filters.business_type===kind}" :aria-pressed="w.filters.business_type===kind" @click="w.filters.business_type=kind;w.applyFilters()">{{ kind||'全部' }}</button></div>
            <label class="search-field"><AppIcon name="search" /><input id="inquiry-search" v-model="w.filters.q" @input="w.search" placeholder="搜索询价、客户或编号" aria-label="搜索询价"><button v-if="w.filters.q" aria-label="清空搜索" @click="w.filters.q='';w.applyFilters()"><AppIcon name="close" /></button><kbd v-else>⌘ / Ctrl K</kbd></label>
            <select v-model="w.filters.scope" aria-label="责任范围" @change="w.applyFilters"><option value="all">全部参与</option><option value="mine">我负责的</option><option value="collaborating">我协作的</option></select>
            <select v-model="w.filters.status" aria-label="询价状态" @change="w.applyFilters"><option>协作中</option><option>已归档</option><option value="">全部状态</option></select>
            <select v-model="w.filters.sort" aria-label="排序方式" @change="w.applyFilters"><option value="updated">最近更新</option><option value="delivery">期望交期</option><option value="name">名称排序</option></select>
          </div>
          <div v-if="w.loading" class="loading-inline" role="status"><span class="spinner"></span>正在读取…</div>
          <div v-if="w.rows.length" class="list-panel">
            <div class="desktop-records table-scroll"><table class="inquiry-table"><thead><tr><th>询价 / 客户</th><th v-if="w.columns.business">类型</th><th v-if="w.columns.people">负责人 / 协作</th><th v-if="w.columns.date">期望交期</th><th v-if="w.columns.status">状态</th><th v-if="w.columns.updated">最近更新</th><th class="row-arrow"><span class="sr-only">打开</span></th></tr></thead><tbody><tr v-for="row in w.rows" :key="row.name" @click="w.openInquiry(row.name)"><td><button class="record-link" @click.stop="w.openInquiry(row.name)">{{ row.title }}</button><small class="row-subtitle">{{ row.customer_name }}</small></td><td v-if="w.columns.business"><span :class="['type-label',{'metal':row.business_type==='钣金'}]">{{ row.business_type }}</span></td><td v-if="w.columns.people"><span>{{ row.responsible_name||w.userName(row.responsible) }}</span><small class="row-subtitle">{{ row.collaborator_name||w.userName(row.collaborator) }}</small></td><td v-if="w.columns.date" class="tabular">{{ row.expected_date||'未设置' }}</td><td v-if="w.columns.status"><StatusBadge :value="row.status" /></td><td v-if="w.columns.updated" class="muted tabular">{{ stamp(row.modified,true) }}</td><td class="row-arrow"><AppIcon name="right" /></td></tr></tbody></table></div>
            <div class="mobile-records"><button v-for="row in w.rows" :key="row.name" class="mobile-record" @click="w.openInquiry(row.name)"><span class="heading-inline"><span class="type-label">{{ row.business_type }}</span><StatusBadge :value="row.status" /><span class="grow"></span><AppIcon name="right" /></span><strong>{{ row.title }}</strong><span class="muted">{{ row.customer_name }}</span><span class="mobile-record-meta"><span>{{ row.responsible_name||w.userName(row.responsible) }}</span><span>{{ row.expected_date?'交期 '+row.expected_date:'交期待定' }}</span></span></button></div>
            <div class="list-footer"><span>{{ w.total }} 笔询价</span><div v-if="w.total>20||w.filters.page>1" class="pagination"><Button icon="back" aria-label="上一页" variant="ghost" :disabled="w.filters.page<=1||w.loading" @click="w.listPage(w.filters.page-1)" /><span>{{ w.filters.page }} / {{ Math.max(1,Math.ceil(w.total/20)) }}</span><Button icon="arrow" aria-label="下一页" variant="ghost" :disabled="w.filters.page*20>=w.total||w.loading" @click="w.listPage(w.filters.page+1)" /></div></div>
          </div>
          <EmptyState v-else-if="!w.loading" icon="search" title="没有找到匹配的询价" description="调整搜索或筛选条件，再试一次。"><Button @click="Object.assign(w.filters,{q:'',business_type:'',scope:'all',status:'协作中'});w.applyFilters()">清除筛选</Button></EmptyState>
        </template>

        <template v-else-if="w.view==='tasks'">
          <div class="page-heading"><div><h1>我的工作</h1><p v-if="w.inbox.counts.all" class="muted">{{ w.inbox.counts.all }} 项需要处理</p></div><Button icon="list" @click="w.navigate('/inquiries')">查看询价</Button></div>
          <div class="work-tabs" aria-label="待办类型"><button v-for="[key,label] in inboxTabs" :key="key" :class="{active:w.inboxKind===key}" :aria-pressed="w.inboxKind===key" @click="w.chooseInbox(key)">{{ label }}<span v-if="w.inbox.counts[key]">{{ w.inbox.counts[key] }}</span></button></div>
          <div v-if="w.loading" class="loading-inline" role="status"><span class="spinner"></span>读取待办…</div>
          <div v-if="w.inbox.rows.length" class="list-panel inbox-list"><button v-for="item in w.inbox.rows" :key="item.name" class="inbox-row" @click="w.openInquiry(item.inquiry,item.target_type==='ai'?'ai':'tasks',item.name)"><span :class="['inbox-icon',item.kind]"><AppIcon :name="item.kind==='ai'?'sparkles':item.kind==='confirm'?'circleCheck':item.kind==='held'?'clock':'inbox'" /></span><span class="grow"><strong>{{ item.title }}</strong><small>{{ item.inquiry_title }} · {{ item.customer_name }}</small></span><span v-if="item.stale" class="muted stale-text">资料已更新</span><StatusBadge :value="item.status" /><span class="inbox-time muted">{{ stamp(item.modified,true) }}</span><AppIcon name="right" /></button><div v-if="w.inbox.total>30" class="list-footer"><span>{{ w.inbox.total }} 项</span><div class="pagination"><Button icon="back" aria-label="上一页待办" :disabled="w.inboxPage<=1" @click="w.chooseInbox(w.inboxKind,w.inboxPage-1)" /><span>{{ w.inboxPage }}</span><Button icon="arrow" aria-label="下一页待办" :disabled="w.inboxPage*30>=w.inbox.total" @click="w.chooseInbox(w.inboxKind,w.inboxPage+1)" /></div></div></div>
          <EmptyState v-else-if="!w.loading" icon="circleCheck" title="当前没有待处理事项" description="有需要你处理的任务时，会显示在这里。" />
          <section v-if="w.recent.length" class="recent-section"><div class="section-heading"><h2>最近更新的询价</h2><Button variant="ghost" icon="arrow" @click="w.navigate('/inquiries')">全部询价</Button></div><div class="recent-list"><button v-for="row in w.recent" :key="row.name" @click="w.openInquiry(row.name)"><span class="type-label">{{ row.business_type }}</span><span class="grow"><strong>{{ row.title }}</strong><small>{{ row.customer_name }}</small></span><span class="muted">{{ stamp(row.modified,true) }}</span><AppIcon name="right" /></button></div></section>
        </template>

        <template v-else-if="w.selected">
          <header class="detail-heading"><div class="detail-title"><div class="heading-inline"><span :class="['type-label',{metal:w.selected.business_type==='钣金'}]">{{ w.selected.business_type }}</span><StatusBadge :value="w.selected.status" /></div><h1>{{ w.selected.title }}</h1><p>{{ w.selected.customer_name }}<span class="separator">·</span>{{ w.userName(w.selected.responsible) }}负责<span v-if="w.selected.expected_date" class="detail-date"><span class="separator">·</span>交期 {{ w.selected.expected_date }}</span></p></div><div class="toolbar-actions"><Button v-if="w.selected.can_edit&&w.isOpen" icon="edit" :disabled="w.busy" @click="w.editInquiry()">编辑</Button><details class="popover detail-menu"><summary class="button secondary" aria-label="更多询价操作"><AppIcon name="more" /></summary><div class="popover-content"><button :disabled="w.busy" @click="menuAction(w.exportBundle)"><AppIcon name="download" />生成资料包</button><button @click="menuAction(()=>w.changeTab('exports'))"><AppIcon name="package" />查看导出包<span>{{ w.selected.exports.length }}</span></button><button @click="menuAction(copyLink)"><AppIcon name="link" />复制页面链接</button><hr v-if="w.selected.can_edit"><button v-if="w.selected.can_edit" :disabled="w.busy" @click="menuAction(()=>w.openModal('archive',{expected_revision:w.selected.revision,status:w.isOpen?'已归档':'协作中'}))"><AppIcon name="archive" />{{ w.isOpen?'归档询价':'恢复协作' }}</button></div></details></div></header>
          <div class="detail-tabs" role="tablist" aria-label="询价内容"><button v-for="([key,label],index) in detailTabs" :key="key" :id="'tab-'+key" role="tab" :aria-controls="'panel-'+key" :aria-selected="w.tab===key" :tabindex="w.tab===key||(w.tab==='exports'&&index===0)?0:-1" :class="{active:w.tab===key}" @click="w.changeTab(key)" @keydown="tabKey($event,index)">{{ label }}<span v-if="key==='documents'&&w.selected.documents.length">{{ w.selected.documents.length }}</span><span v-if="key==='tasks'&&w.remaining">{{ w.remaining }}</span></button><span class="grow"></span><span v-if="w.busy||w.loading" class="tab-sync" role="status"><span class="spinner"></span>{{ w.busy?'处理中':'同步中' }}</span></div>
          <section v-if="w.tab==='overview'" id="panel-overview" role="tabpanel" aria-labelledby="tab-overview" class="overview-grid">
            <div class="overview-main"><section class="panel"><div class="section-heading"><h2>需求信息</h2></div><dl class="info-grid"><div><dt>客户名称</dt><dd>{{ w.selected.customer_name }}</dd></div><div><dt>期望交期</dt><dd>{{ w.selected.expected_date||'待确认' }}</dd></div><div><dt>负责部门</dt><dd>{{ w.department(w.selected.department) }}</dd></div><div><dt>技术协作者</dt><dd>{{ w.userName(w.selected.collaborator) }}</dd></div></dl><div v-if="w.selected.notes" class="requirement-notes"><h3>需求说明</h3><p>{{ w.selected.notes }}</p></div><button v-else-if="w.selected.can_edit&&w.isOpen" class="text-action" @click="w.editInquiry()"><AppIcon name="plus" />补充需求说明</button></section>
            <section class="panel products-panel"><div class="section-heading"><h2>产品明细 <span class="count">{{ w.selected.items.length }}</span></h2></div><div class="table-scroll"><table class="products"><thead><tr><th>产品名称</th><th>数量</th><th>规格说明</th></tr></thead><tbody><tr v-for="item in w.selected.items" :key="item.line_id"><td>{{ item.product_name }}</td><td class="tabular">{{ item.quantity }} {{ item.unit }}</td><td>{{ item.specification||'待补充' }}</td></tr></tbody></table></div></section></div>
            <aside class="overview-aside"><section class="panel"><div class="section-heading"><h3>协作任务</h3><Button variant="ghost" icon="arrow" aria-label="查看协作任务" @click="w.changeTab('tasks')" /></div><button v-for="task in w.selected.tasks.filter(t=>t.status!=='已完成').slice(0,3)" :key="task.name" class="related-item" @click="w.changeTab('tasks',task.name)"><span>{{ task.title }}</span><small>{{ task.status }} · {{ w.userName(task.assigned_to) }}</small></button><p v-if="!w.remaining" class="muted compact-empty">暂无待处理任务</p><Button v-if="w.selected.can_edit&&w.isOpen" variant="ghost" icon="plus" @click="w.taskModal">分派任务</Button></section><section v-if="w.selected.documents.length" class="panel"><div class="section-heading"><h3>资料</h3><Button variant="ghost" icon="arrow" aria-label="查看全部资料" @click="w.changeTab('documents')" /></div><button v-for="doc in w.selected.documents.slice(0,3)" :key="doc.name" class="related-file" @click="w.changeTab('documents')"><AppIcon name="file" /><span>{{ doc.title }}</span><small>V{{ doc.current_version }}</small></button></section><div class="record-meta"><span>记录版本 {{ w.selected.revision }}</span><button class="text-action" @click="w.changeTab('activities')">查看历史</button></div></aside>
          </section>
          <section v-if="w.tab==='documents'" id="panel-documents" role="tabpanel" aria-labelledby="tab-documents"><DocumentsPanel :inquiry="w.selected" :user-name="w.userName" @upload="w.upload" /></section>
          <section v-if="w.tab==='tasks'" id="panel-tasks" role="tabpanel" aria-labelledby="tab-tasks"><div class="section-heading"><div class="segmented" aria-label="任务状态"><button :class="{selected:taskFilter==='open'}" @click="taskFilter='open'">进行中</button><button :class="{selected:taskFilter==='done'}" @click="taskFilter='done'">已完成</button><button :class="{selected:taskFilter==='all'}" @click="taskFilter='all'">全部</button></div><Button v-if="w.selected.can_edit&&w.isOpen" variant="primary" icon="plus" @click="w.taskModal">分派任务</Button></div><EmptyState v-if="!taskRows.length" icon="inbox" title="这里还没有任务" description="需要补充或核对的事项可以分派给协作者。" /><div class="task-list"><article v-for="task in taskRows" :key="task.name" :id="'task-'+task.name" :class="['panel task-card',{'focused-task':w.target===task.name}]"><header><div><h3>{{ task.title }}</h3><p>{{ w.userName(task.assigned_to) }}处理<span class="separator">·</span>{{ stamp(task.creation) }}</p></div><StatusBadge :value="task.status" /></header><p v-if="task.description" class="task-description">{{ task.description }}</p><div v-if="task.reply" class="reply-block"><strong>最近回复</strong><p>{{ task.reply }}</p></div><footer v-if="w.isOpen&&task.status!=='已完成'"><span v-if="task.status==='待确认'" class="muted">{{ w.selected.can_edit?'回复已提交，等待你确认':'等待负责人确认' }}</span><span class="grow"></span><Button v-if="task.status==='待处理'&&(task.assigned_to===w.user||w.boot.can_manage)" variant="primary" :disabled="w.busy" @click="w.actionModal(task,'reply')">回复任务</Button><template v-if="w.selected.can_edit"><Button v-if="['待处理','待确认'].includes(task.status)" variant="ghost" :disabled="w.busy" @click="w.actionModal(task,'hold')">挂起</Button><Button v-if="task.status==='待确认'" :disabled="w.busy" @click="w.actionModal(task,'return')">退回补充</Button><Button v-if="task.status==='待确认'" variant="primary" icon="check" :disabled="w.busy" @click="w.taskAction(task,'confirm')">确认完成</Button><Button v-if="task.status==='已挂起'" :disabled="w.busy" @click="w.taskAction(task,'resume')">恢复任务</Button></template></footer></article></div></section>
          <section v-if="w.tab==='ai'" id="panel-ai" role="tabpanel" aria-labelledby="tab-ai"><AiPanel :key="w.selected.name" :inquiry="w.selected" :requested-run="w.target" :confirm-action="w.ask" :user-name="w.userName" @changed="w.refresh" @dirty="w.childDirty=$event" @selected="w.changeTab('ai',$event)" /></section>
          <section v-if="w.tab==='activities'" id="panel-activities" role="tabpanel" aria-labelledby="tab-activities" class="activity-panel"><div class="section-heading"><h2>操作历史</h2><span class="muted">{{ w.selected.activities.length }} 条记录</span></div><div class="timeline"><article v-for="item in w.selected.activities" :key="item.name"><span class="timeline-dot"></span><div class="grow"><strong>{{ item.summary }}</strong><p class="activity-meta">{{ w.userName(item.actor) }}<span class="separator">·</span>{{ stamp(item.creation) }}</p><details v-if="activityRows(item.details_json).length" class="activity-details"><summary>查看变化</summary><div v-for="row in activityRows(item.details_json)" :key="row.field" class="change-row"><strong>{{ row.label }}</strong><div v-if="row.before!==undefined"><small>修改前</small><p>{{ row.before }}</p></div><div><small>{{ row.before!==undefined?'修改后':'内容' }}</small><p>{{ row.after }}</p></div></div></details></div></article></div></section>
          <section v-if="w.tab==='exports'" class="exports-panel"><div class="section-heading"><h2>导出资料包</h2><Button variant="primary" icon="download" :loading="w.busy" @click="w.exportBundle">生成资料包</Button></div><p class="muted export-description">包含询价快照、各版原件、协作与审核记录。</p><EmptyState v-if="!w.selected.exports.length" icon="package" title="还没有生成资料包" description="生成后可下载完整 ZIP 文件。" /><div v-else class="panel export-list"><div v-for="item in w.selected.exports" :key="item.name" class="export-row"><span class="file-tile"><AppIcon name="package" /></span><div class="grow"><strong>询价资料包 · 记录版本 {{ item.inquiry_revision }}</strong><small>{{ stamp(item.creation) }} · {{ w.userName(item.requested_by) }}</small></div><DownloadButton kind="export" :name="item.name" label="下载资料包" /></div></div></section>
        </template>
        <div v-else-if="w.loading" class="loading-inline" role="status"><span class="spinner"></span>正在打开询价…</div>
        <EmptyState v-else-if="!w.error" icon="file" title="未找到这笔询价"><Button @click="w.navigate('/inquiries')">返回询价</Button></EmptyState>
      </div>
    </main>
    <WorkspaceForm :w="w" />
    <dialog :ref="el=>w.confirmDialog=el" class="modal confirm-modal" aria-labelledby="confirm-title" aria-describedby="confirm-message" @cancel.prevent="w.answerConfirmation(false)">
      <form method="dialog" @submit.prevent="w.answerConfirmation(true)"><header class="modal-header"><h2 id="confirm-title">确认操作</h2></header><div class="modal-body"><p id="confirm-message">{{ w.confirmation }}</p></div><footer class="modal-footer"><span class="grow"></span><Button @click="w.answerConfirmation(false)">取消</Button><Button variant="primary" type="submit">继续</Button></footer></form>
    </dialog>
  </div>
</template>
